package opsigo.com.domainlayer.model.summary

data class PassengersItemModel (
    var otherPhone: Any? = null,
    var email: Any? = null,
    var passportExpire: Any? = null,
    var idNumber: Any? = null,
    var employeeNik: Any? = null,
    var index: Int? = null,
    var tripTrainId: String? = null,
    var mobilePhone: String? = null,
    var remarksPax: List<Any?>? = null,
    var jobTitleId: String? = null,
    var passport: PassportModel? = null,
    var passportOrigin: Any? = null,
    var remarks: Any? = null,
    var ticketNumber: Any? = null,
    var seatText: String? = null,
    var paxType: Any? = null,
    var employeeId: String? = null,
    var identityType: Any? = null,
    var retSsr: List<Any?>? = null,
    var firstName: String? = null,
    var budgetId: Any? = null,
    var ssrs: List<Any?>? = null,
    var title: String? = null,
    var sequence: Any? = null,
    var nationality: String? = null,
    var costCenterId: Any? = null,
    var depSsr: List<Any?>? = null,
    var seats: List<Any?>? = null,
    var type: String? = null,
    var isSeniorCitizen: Boolean? = null,
    var seatName: Any? = null,
    var homePhone: String? = null,
    var passportNumber: Any? = null,
    var id: String? = null,
    var lastName: String? = null,
    var adultAssoc: Any? = null,
    var seatNumber: Any? = null,
    var tripFlightId: String? = null,
    var companyCode: Any? = null,
    var birthDate: Any? = null,
    val identityNumber: Any? = null
)