package opsigo.com.domainlayer.model.summary

data class TripFlightsItemsModel (

//        var bookingDate: String? = null,
//        var tripPlanId: Any? = null,
//        var isRefundable: Boolean? = null,
        var id: String? = null,
        var tripItemId: String? = null,
        var pnrId: String? = null,
        var pnrCode: String? = null,
        var airline: Int? = null,
        var origin: String? = null,
        var destination: String? = null,

        var segments: List<SegmentsItemModel?>? = null,
//        var payments: List<PaymentsItemModel?>? = null,
//        var originView: String? = null,
//        var actionDate: String? = null,
//        var isPostedHipchat: Boolean? = null,
//        var remarks: List<Any?>? = null,
//        var ticketNumber: String? = null,
//        var flightType: Int? = null,
//        var prgText: String? = null,
//        var child: Int? = null,
//        var opsigoStatus: Any? = null,
//        var paymentStatus: Any? = null,
//        var flightTypeView: String? = null,
//        var status: String? = null,
//        var paymentReff: Any? = null,
//        var paymentTimeLimit: String? = null,
//        var isEmailSent: Boolean? = null,
//        var ticketedDate: Any? = null,
//        var poNumber: Any? = null,
//        var ticketDocName: Any? = null,
//        var bookingDateView: String? = null,
//        var hasCostCenterUpdated: Boolean? = null,

//        var flightDurationPerNum: List<String?>? = null,
//        var timeLimitView: String? = null,
//        var passengers: List<PassengersItemModel?>? = null,
//        var approvedBy: String? = null,
//        var destinationView: String? = null,
//        var travelAgent: Any? = null,
//        var prgNum: Int? = null,
//        var jobProgress: JobProgressModel? = null,

//        var isRemoved: Boolean? = null,
//        var amountBeforeReserved: Int? = null,
//        var opsigoLastSync: String? = null,
//        var voidDate: String? = null,
//        var diffAmountInfo: Any? = null,
//        var infant: Int? = null,
//        var linkReference: String? = null,
//        var actionDateView: String? = null,
//        var ticketedDateView: Any? = null,
//        var adult: Int? = null,
//        var prgJobType: String? = null,
//        var remarkReject: String? = null,
//        var timeLimit: String? = null,
//        var airlineView: String? = null,
        var amount: Double? = null,
//        var contact: ContactModel? = null,
        var isVoid: Boolean? = null
//        var ticketDocUrl: Any? = null,

)